[package]
name = "pam-rampdelay"
version = "0.1.0"
authors = ["34n0 <34n0@immerda.ch>"]

[lib]
name = "pam_rampdelay"
crate-type = ["cdylib"]

[dependencies]
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
pam-bindings = "0.1.1"
pam-client = "0.5.0"

