name: cargo-unit-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: rs-cargo
      uses: clechasseur/rs-cargo@v2.0.1
      with:
        command: test --release --lib
        working-directory: .
